/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.EstilosActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EstilosExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EstilosActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EstilosActivator.getInstance().getInjector(EstilosActivator.ORG_XTEXT_ESTILOS);
	}
	
}
