/*
* generated by Xtext
*/
package org.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CatalogoGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RootSistemaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RootSistema");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRootSistemaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cEmpresaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEmpresaAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEmpresaEmpresaParserRuleCall_3_0 = (RuleCall)cEmpresaAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//RootSistema:
		//	"RootSistema" "{" "empresa" empresa=Empresa "}";
		public ParserRule getRule() { return rule; }

		//"RootSistema" "{" "empresa" empresa=Empresa "}"
		public Group getGroup() { return cGroup; }

		//"RootSistema"
		public Keyword getRootSistemaKeyword_0() { return cRootSistemaKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"empresa"
		public Keyword getEmpresaKeyword_2() { return cEmpresaKeyword_2; }

		//empresa=Empresa
		public Assignment getEmpresaAssignment_3() { return cEmpresaAssignment_3; }

		//Empresa
		public RuleCall getEmpresaEmpresaParserRuleCall_3_0() { return cEmpresaEmpresaParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class EmpresaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Empresa");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEmpresaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cNombreKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cNombreAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_2_1_0 = (RuleCall)cNombreAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDireccionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDireccionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDireccionEStringParserRuleCall_3_1_0 = (RuleCall)cDireccionAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cEmailKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cEmailAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cEmailEStringParserRuleCall_4_1_0 = (RuleCall)cEmailAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cTelefonoKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cTelefonoAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cTelefonoEStringParserRuleCall_5_1_0 = (RuleCall)cTelefonoAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDescripcionKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDescripcionAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDescripcionEStringParserRuleCall_6_1_0 = (RuleCall)cDescripcionAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cUrlImagenKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cUrlImagenAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cUrlImagenEStringParserRuleCall_7_1_0 = (RuleCall)cUrlImagenAssignment_7_1.eContents().get(0);
		private final Keyword cCatalogoKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cCatalogoAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cCatalogoCatalogoParserRuleCall_9_0 = (RuleCall)cCatalogoAssignment_9.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Empresa:
		//	"Empresa" "{" ("nombre" nombre=EString)? ("direccion" direccion=EString)? ("email" email=EString)? ("telefono"
		//	telefono=EString)? ("descripcion" descripcion=EString)? ("urlImagen" urlImagen=EString)? "catalogo" catalogo=Catalogo
		//	"}";
		public ParserRule getRule() { return rule; }

		//"Empresa" "{" ("nombre" nombre=EString)? ("direccion" direccion=EString)? ("email" email=EString)? ("telefono"
		//telefono=EString)? ("descripcion" descripcion=EString)? ("urlImagen" urlImagen=EString)? "catalogo" catalogo=Catalogo
		//"}"
		public Group getGroup() { return cGroup; }

		//"Empresa"
		public Keyword getEmpresaKeyword_0() { return cEmpresaKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("nombre" nombre=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"nombre"
		public Keyword getNombreKeyword_2_0() { return cNombreKeyword_2_0; }

		//nombre=EString
		public Assignment getNombreAssignment_2_1() { return cNombreAssignment_2_1; }

		//EString
		public RuleCall getNombreEStringParserRuleCall_2_1_0() { return cNombreEStringParserRuleCall_2_1_0; }

		//("direccion" direccion=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"direccion"
		public Keyword getDireccionKeyword_3_0() { return cDireccionKeyword_3_0; }

		//direccion=EString
		public Assignment getDireccionAssignment_3_1() { return cDireccionAssignment_3_1; }

		//EString
		public RuleCall getDireccionEStringParserRuleCall_3_1_0() { return cDireccionEStringParserRuleCall_3_1_0; }

		//("email" email=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"email"
		public Keyword getEmailKeyword_4_0() { return cEmailKeyword_4_0; }

		//email=EString
		public Assignment getEmailAssignment_4_1() { return cEmailAssignment_4_1; }

		//EString
		public RuleCall getEmailEStringParserRuleCall_4_1_0() { return cEmailEStringParserRuleCall_4_1_0; }

		//("telefono" telefono=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"telefono"
		public Keyword getTelefonoKeyword_5_0() { return cTelefonoKeyword_5_0; }

		//telefono=EString
		public Assignment getTelefonoAssignment_5_1() { return cTelefonoAssignment_5_1; }

		//EString
		public RuleCall getTelefonoEStringParserRuleCall_5_1_0() { return cTelefonoEStringParserRuleCall_5_1_0; }

		//("descripcion" descripcion=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"descripcion"
		public Keyword getDescripcionKeyword_6_0() { return cDescripcionKeyword_6_0; }

		//descripcion=EString
		public Assignment getDescripcionAssignment_6_1() { return cDescripcionAssignment_6_1; }

		//EString
		public RuleCall getDescripcionEStringParserRuleCall_6_1_0() { return cDescripcionEStringParserRuleCall_6_1_0; }

		//("urlImagen" urlImagen=EString)?
		public Group getGroup_7() { return cGroup_7; }

		//"urlImagen"
		public Keyword getUrlImagenKeyword_7_0() { return cUrlImagenKeyword_7_0; }

		//urlImagen=EString
		public Assignment getUrlImagenAssignment_7_1() { return cUrlImagenAssignment_7_1; }

		//EString
		public RuleCall getUrlImagenEStringParserRuleCall_7_1_0() { return cUrlImagenEStringParserRuleCall_7_1_0; }

		//"catalogo"
		public Keyword getCatalogoKeyword_8() { return cCatalogoKeyword_8; }

		//catalogo=Catalogo
		public Assignment getCatalogoAssignment_9() { return cCatalogoAssignment_9; }

		//Catalogo
		public RuleCall getCatalogoCatalogoParserRuleCall_9_0() { return cCatalogoCatalogoParserRuleCall_9_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class CatalogoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Catalogo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCatalogoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdCatalogoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdCatalogoAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdCatalogoELongParserRuleCall_2_1_0 = (RuleCall)cIdCatalogoAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNombreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNombreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_3_1_0 = (RuleCall)cNombreAssignment_3_1.eContents().get(0);
		private final Keyword cCategoriasKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCategoriasAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cCategoriasCategoriaParserRuleCall_6_0 = (RuleCall)cCategoriasAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cCategoriasAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cCategoriasCategoriaParserRuleCall_7_1_0 = (RuleCall)cCategoriasAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Catalogo:
		//	"Catalogo" "{" ("idCatalogo" idCatalogo=ELong)? ("nombre" nombre=EString)? "categorias" "{" categorias+=Categoria
		//	("," categorias+=Categoria)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"Catalogo" "{" ("idCatalogo" idCatalogo=ELong)? ("nombre" nombre=EString)? "categorias" "{" categorias+=Categoria (","
		//categorias+=Categoria)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"Catalogo"
		public Keyword getCatalogoKeyword_0() { return cCatalogoKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("idCatalogo" idCatalogo=ELong)?
		public Group getGroup_2() { return cGroup_2; }

		//"idCatalogo"
		public Keyword getIdCatalogoKeyword_2_0() { return cIdCatalogoKeyword_2_0; }

		//idCatalogo=ELong
		public Assignment getIdCatalogoAssignment_2_1() { return cIdCatalogoAssignment_2_1; }

		//ELong
		public RuleCall getIdCatalogoELongParserRuleCall_2_1_0() { return cIdCatalogoELongParserRuleCall_2_1_0; }

		//("nombre" nombre=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"nombre"
		public Keyword getNombreKeyword_3_0() { return cNombreKeyword_3_0; }

		//nombre=EString
		public Assignment getNombreAssignment_3_1() { return cNombreAssignment_3_1; }

		//EString
		public RuleCall getNombreEStringParserRuleCall_3_1_0() { return cNombreEStringParserRuleCall_3_1_0; }

		//"categorias"
		public Keyword getCategoriasKeyword_4() { return cCategoriasKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//categorias+=Categoria
		public Assignment getCategoriasAssignment_6() { return cCategoriasAssignment_6; }

		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_6_0() { return cCategoriasCategoriaParserRuleCall_6_0; }

		//("," categorias+=Categoria)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//categorias+=Categoria
		public Assignment getCategoriasAssignment_7_1() { return cCategoriasAssignment_7_1; }

		//Categoria
		public RuleCall getCategoriasCategoriaParserRuleCall_7_1_0() { return cCategoriasCategoriaParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class ELongElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ELong");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//ELong returns ecore::ELong:
		//	"-"? INT;
		public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class CategoriaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Categoria");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCategoriaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdCategoriaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdCategoriaAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdCategoriaELongParserRuleCall_2_1_0 = (RuleCall)cIdCategoriaAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNombreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNombreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_3_1_0 = (RuleCall)cNombreAssignment_3_1.eContents().get(0);
		private final Keyword cProductosKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cProductosAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cProductosProductoParserRuleCall_6_0 = (RuleCall)cProductosAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProductosAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cProductosProductoParserRuleCall_7_1_0 = (RuleCall)cProductosAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Categoria:
		//	"Categoria" "{" ("idCategoria" idCategoria=ELong)? ("nombre" nombre=EString)? "productos" "{" productos+=Producto
		//	("," productos+=Producto)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"Categoria" "{" ("idCategoria" idCategoria=ELong)? ("nombre" nombre=EString)? "productos" "{" productos+=Producto (","
		//productos+=Producto)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"Categoria"
		public Keyword getCategoriaKeyword_0() { return cCategoriaKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("idCategoria" idCategoria=ELong)?
		public Group getGroup_2() { return cGroup_2; }

		//"idCategoria"
		public Keyword getIdCategoriaKeyword_2_0() { return cIdCategoriaKeyword_2_0; }

		//idCategoria=ELong
		public Assignment getIdCategoriaAssignment_2_1() { return cIdCategoriaAssignment_2_1; }

		//ELong
		public RuleCall getIdCategoriaELongParserRuleCall_2_1_0() { return cIdCategoriaELongParserRuleCall_2_1_0; }

		//("nombre" nombre=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"nombre"
		public Keyword getNombreKeyword_3_0() { return cNombreKeyword_3_0; }

		//nombre=EString
		public Assignment getNombreAssignment_3_1() { return cNombreAssignment_3_1; }

		//EString
		public RuleCall getNombreEStringParserRuleCall_3_1_0() { return cNombreEStringParserRuleCall_3_1_0; }

		//"productos"
		public Keyword getProductosKeyword_4() { return cProductosKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//productos+=Producto
		public Assignment getProductosAssignment_6() { return cProductosAssignment_6; }

		//Producto
		public RuleCall getProductosProductoParserRuleCall_6_0() { return cProductosProductoParserRuleCall_6_0; }

		//("," productos+=Producto)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//productos+=Producto
		public Assignment getProductosAssignment_7_1() { return cProductosAssignment_7_1; }

		//Producto
		public RuleCall getProductosProductoParserRuleCall_7_1_0() { return cProductosProductoParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class ProductoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Producto");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cIdProductoKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cIdProductoAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cIdProductoELongParserRuleCall_2_1_0 = (RuleCall)cIdProductoAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNombreKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNombreAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNombreEStringParserRuleCall_3_1_0 = (RuleCall)cNombreAssignment_3_1.eContents().get(0);
		private final Keyword cAtributosKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAtributosAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAtributosAtributoParserRuleCall_6_0 = (RuleCall)cAtributosAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAtributosAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAtributosAtributoParserRuleCall_7_1_0 = (RuleCall)cAtributosAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Producto:
		//	"Producto" "{" ("idProducto" idProducto=ELong)? ("nombre" nombre=EString)? "atributos" "{" atributos+=Atributo (","
		//	atributos+=Atributo)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"Producto" "{" ("idProducto" idProducto=ELong)? ("nombre" nombre=EString)? "atributos" "{" atributos+=Atributo (","
		//atributos+=Atributo)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"Producto"
		public Keyword getProductoKeyword_0() { return cProductoKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("idProducto" idProducto=ELong)?
		public Group getGroup_2() { return cGroup_2; }

		//"idProducto"
		public Keyword getIdProductoKeyword_2_0() { return cIdProductoKeyword_2_0; }

		//idProducto=ELong
		public Assignment getIdProductoAssignment_2_1() { return cIdProductoAssignment_2_1; }

		//ELong
		public RuleCall getIdProductoELongParserRuleCall_2_1_0() { return cIdProductoELongParserRuleCall_2_1_0; }

		//("nombre" nombre=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"nombre"
		public Keyword getNombreKeyword_3_0() { return cNombreKeyword_3_0; }

		//nombre=EString
		public Assignment getNombreAssignment_3_1() { return cNombreAssignment_3_1; }

		//EString
		public RuleCall getNombreEStringParserRuleCall_3_1_0() { return cNombreEStringParserRuleCall_3_1_0; }

		//"atributos"
		public Keyword getAtributosKeyword_4() { return cAtributosKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//atributos+=Atributo
		public Assignment getAtributosAssignment_6() { return cAtributosAssignment_6; }

		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_6_0() { return cAtributosAtributoParserRuleCall_6_0; }

		//("," atributos+=Atributo)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//atributos+=Atributo
		public Assignment getAtributosAssignment_7_1() { return cAtributosAssignment_7_1; }

		//Atributo
		public RuleCall getAtributosAtributoParserRuleCall_7_1_0() { return cAtributosAtributoParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class AtributoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atributo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cAtributoAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAtributoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cIdAtributoKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cIdAtributoAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cIdAtributoELongParserRuleCall_3_1_0 = (RuleCall)cIdAtributoAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNombreAtributoKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNombreAtributoAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNombreAtributoEStringParserRuleCall_4_1_0 = (RuleCall)cNombreAtributoAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cValorAtributoKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cValorAtributoAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cValorAtributoEStringParserRuleCall_5_1_0 = (RuleCall)cValorAtributoAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cTipoDatoKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTipoDatoAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTipoDatoEStringParserRuleCall_6_1_0 = (RuleCall)cTipoDatoAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Atributo:
		//	{Atributo} "Atributo" "{" ("idAtributo" idAtributo=ELong)? ("nombreAtributo" nombreAtributo=EString)?
		//	("valorAtributo" valorAtributo=EString)? ("tipoDato" tipoDato=EString)? "}";
		public ParserRule getRule() { return rule; }

		//{Atributo} "Atributo" "{" ("idAtributo" idAtributo=ELong)? ("nombreAtributo" nombreAtributo=EString)? ("valorAtributo"
		//valorAtributo=EString)? ("tipoDato" tipoDato=EString)? "}"
		public Group getGroup() { return cGroup; }

		//{Atributo}
		public Action getAtributoAction_0() { return cAtributoAction_0; }

		//"Atributo"
		public Keyword getAtributoKeyword_1() { return cAtributoKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("idAtributo" idAtributo=ELong)?
		public Group getGroup_3() { return cGroup_3; }

		//"idAtributo"
		public Keyword getIdAtributoKeyword_3_0() { return cIdAtributoKeyword_3_0; }

		//idAtributo=ELong
		public Assignment getIdAtributoAssignment_3_1() { return cIdAtributoAssignment_3_1; }

		//ELong
		public RuleCall getIdAtributoELongParserRuleCall_3_1_0() { return cIdAtributoELongParserRuleCall_3_1_0; }

		//("nombreAtributo" nombreAtributo=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"nombreAtributo"
		public Keyword getNombreAtributoKeyword_4_0() { return cNombreAtributoKeyword_4_0; }

		//nombreAtributo=EString
		public Assignment getNombreAtributoAssignment_4_1() { return cNombreAtributoAssignment_4_1; }

		//EString
		public RuleCall getNombreAtributoEStringParserRuleCall_4_1_0() { return cNombreAtributoEStringParserRuleCall_4_1_0; }

		//("valorAtributo" valorAtributo=EString)?
		public Group getGroup_5() { return cGroup_5; }

		//"valorAtributo"
		public Keyword getValorAtributoKeyword_5_0() { return cValorAtributoKeyword_5_0; }

		//valorAtributo=EString
		public Assignment getValorAtributoAssignment_5_1() { return cValorAtributoAssignment_5_1; }

		//EString
		public RuleCall getValorAtributoEStringParserRuleCall_5_1_0() { return cValorAtributoEStringParserRuleCall_5_1_0; }

		//("tipoDato" tipoDato=EString)?
		public Group getGroup_6() { return cGroup_6; }

		//"tipoDato"
		public Keyword getTipoDatoKeyword_6_0() { return cTipoDatoKeyword_6_0; }

		//tipoDato=EString
		public Assignment getTipoDatoAssignment_6_1() { return cTipoDatoAssignment_6_1; }

		//EString
		public RuleCall getTipoDatoEStringParserRuleCall_6_1_0() { return cTipoDatoEStringParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final RootSistemaElements pRootSistema;
	private final EmpresaElements pEmpresa;
	private final EStringElements pEString;
	private final CatalogoElements pCatalogo;
	private final ELongElements pELong;
	private final CategoriaElements pCategoria;
	private final ProductoElements pProducto;
	private final AtributoElements pAtributo;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CatalogoGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRootSistema = new RootSistemaElements();
		this.pEmpresa = new EmpresaElements();
		this.pEString = new EStringElements();
		this.pCatalogo = new CatalogoElements();
		this.pELong = new ELongElements();
		this.pCategoria = new CategoriaElements();
		this.pProducto = new ProductoElements();
		this.pAtributo = new AtributoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Catalogo".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RootSistema:
	//	"RootSistema" "{" "empresa" empresa=Empresa "}";
	public RootSistemaElements getRootSistemaAccess() {
		return pRootSistema;
	}
	
	public ParserRule getRootSistemaRule() {
		return getRootSistemaAccess().getRule();
	}

	//Empresa:
	//	"Empresa" "{" ("nombre" nombre=EString)? ("direccion" direccion=EString)? ("email" email=EString)? ("telefono"
	//	telefono=EString)? ("descripcion" descripcion=EString)? ("urlImagen" urlImagen=EString)? "catalogo" catalogo=Catalogo
	//	"}";
	public EmpresaElements getEmpresaAccess() {
		return pEmpresa;
	}
	
	public ParserRule getEmpresaRule() {
		return getEmpresaAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Catalogo:
	//	"Catalogo" "{" ("idCatalogo" idCatalogo=ELong)? ("nombre" nombre=EString)? "categorias" "{" categorias+=Categoria
	//	("," categorias+=Categoria)* "}" "}";
	public CatalogoElements getCatalogoAccess() {
		return pCatalogo;
	}
	
	public ParserRule getCatalogoRule() {
		return getCatalogoAccess().getRule();
	}

	//ELong returns ecore::ELong:
	//	"-"? INT;
	public ELongElements getELongAccess() {
		return pELong;
	}
	
	public ParserRule getELongRule() {
		return getELongAccess().getRule();
	}

	//Categoria:
	//	"Categoria" "{" ("idCategoria" idCategoria=ELong)? ("nombre" nombre=EString)? "productos" "{" productos+=Producto
	//	("," productos+=Producto)* "}" "}";
	public CategoriaElements getCategoriaAccess() {
		return pCategoria;
	}
	
	public ParserRule getCategoriaRule() {
		return getCategoriaAccess().getRule();
	}

	//Producto:
	//	"Producto" "{" ("idProducto" idProducto=ELong)? ("nombre" nombre=EString)? "atributos" "{" atributos+=Atributo (","
	//	atributos+=Atributo)* "}" "}";
	public ProductoElements getProductoAccess() {
		return pProducto;
	}
	
	public ParserRule getProductoRule() {
		return getProductoAccess().getRule();
	}

	//Atributo:
	//	{Atributo} "Atributo" "{" ("idAtributo" idAtributo=ELong)? ("nombreAtributo" nombreAtributo=EString)?
	//	("valorAtributo" valorAtributo=EString)? ("tipoDato" tipoDato=EString)? "}";
	public AtributoElements getAtributoAccess() {
		return pAtributo;
	}
	
	public ParserRule getAtributoRule() {
		return getAtributoAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
