/*
* generated by Xtext
*/
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CatalogoStandaloneSetup extends CatalogoStandaloneSetupGenerated{

	public static void doSetup() {
		new CatalogoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

