/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.EstilosGrammarAccess;

public class EstilosParser extends AbstractContentAssistParser {
	
	@Inject
	private EstilosGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalEstilosParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalEstilosParser result = new org.xtext.ui.contentassist.antlr.internal.InternalEstilosParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getTecnologiaAccess().getAlternatives(), "rule__Tecnologia__Alternatives");
					put(grammarAccess.getTamanoLetraAccess().getAlternatives(), "rule__TamanoLetra__Alternatives");
					put(grammarAccess.getRootSistemaAccess().getGroup(), "rule__RootSistema__Group__0");
					put(grammarAccess.getRootSistemaAccess().getGroup_5(), "rule__RootSistema__Group_5__0");
					put(grammarAccess.getVistaAccess().getGroup(), "rule__Vista__Group__0");
					put(grammarAccess.getVistaAccess().getGroup_3(), "rule__Vista__Group_3__0");
					put(grammarAccess.getVistaAccess().getGroup_4(), "rule__Vista__Group_4__0");
					put(grammarAccess.getLetraAccess().getGroup(), "rule__Letra__Group__0");
					put(grammarAccess.getLetraAccess().getGroup_3(), "rule__Letra__Group_3__0");
					put(grammarAccess.getLetraAccess().getGroup_4(), "rule__Letra__Group_4__0");
					put(grammarAccess.getLetraAccess().getGroup_5(), "rule__Letra__Group_5__0");
					put(grammarAccess.getRootSistemaAccess().getVistasAssignment_4(), "rule__RootSistema__VistasAssignment_4");
					put(grammarAccess.getRootSistemaAccess().getVistasAssignment_5_1(), "rule__RootSistema__VistasAssignment_5_1");
					put(grammarAccess.getVistaAccess().getBarraBusquedaAssignment_0(), "rule__Vista__BarraBusquedaAssignment_0");
					put(grammarAccess.getVistaAccess().getColorFondoAssignment_3_1(), "rule__Vista__ColorFondoAssignment_3_1");
					put(grammarAccess.getVistaAccess().getTecnologiaAssignment_4_1(), "rule__Vista__TecnologiaAssignment_4_1");
					put(grammarAccess.getVistaAccess().getLetraAssignment_6(), "rule__Vista__LetraAssignment_6");
					put(grammarAccess.getLetraAccess().getColorLetraAssignment_3_1(), "rule__Letra__ColorLetraAssignment_3_1");
					put(grammarAccess.getLetraAccess().getFuenteAssignment_4_1(), "rule__Letra__FuenteAssignment_4_1");
					put(grammarAccess.getLetraAccess().getTamanoAssignment_5_1(), "rule__Letra__TamanoAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalEstilosParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalEstilosParser) parser;
			typedParser.entryRuleRootSistema();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EstilosGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EstilosGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
