/*
* generated by Xtext
*/
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EstilosStandaloneSetup extends EstilosStandaloneSetupGenerated{

	public static void doSetup() {
		new EstilosStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

