/**
 *
 * $Id$
 */
package catalogo.validation;


/**
 * A sample validator interface for {@link catalogo.Atributo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AtributoValidator {
	boolean validate();

	boolean validateIdAtributo(long value);
	boolean validateNombreAtributo(String value);
	boolean validateValorAtributo(String value);
	boolean validateTipoDato(String value);
}
