/**
 *
 * $Id$
 */
package catalogo.validation;

import catalogo.Categoria;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link catalogo.Catalogo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CatalogoValidator {
	boolean validate();

	boolean validateIdCatalogo(long value);
	boolean validateNombre(String value);
	boolean validateCategorias(EList<Categoria> value);
}
