/**
 *
 * $Id$
 */
package catalogo.validation;

import catalogo.Atributo;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link catalogo.Producto}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductoValidator {
	boolean validate();

	boolean validateIdProducto(long value);
	boolean validateAtributos(EList<Atributo> value);
	boolean validateNombre(String value);
}
