/**
 *
 * $Id$
 */
package arquitectura.validation;

import arquitectura.ComunicacionHttp;
import arquitectura.Controlador;
import arquitectura.EntidadPresentacion;
import arquitectura.Tecnologia;
import arquitectura.Vista;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link arquitectura.CapaPresentacion}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CapaPresentacionValidator {
	boolean validate();

	boolean validateVistas(EList<Vista> value);
	boolean validateControladores(EList<Controlador> value);
	boolean validateComunicacionesHttp(EList<ComunicacionHttp> value);
	boolean validateEntidades(EList<EntidadPresentacion> value);
	boolean validateTecnologia(Tecnologia value);
	boolean validateBarraBusqueda(boolean value);
}
