/**
 *
 * $Id$
 */
package arquitectura.validation;

import arquitectura.BeanNegocio;
import arquitectura.InterfaceNegocio;
import arquitectura.JsonDTO;
import arquitectura.Mapper;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link arquitectura.CapaLogicaNegocio}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CapaLogicaNegocioValidator {
	boolean validate();

	boolean validateInterfaces(EList<InterfaceNegocio> value);
	boolean validateBeans(EList<BeanNegocio> value);
	boolean validateJsonsDTO(EList<JsonDTO> value);
	boolean validateMappers(EList<Mapper> value);
}
