/**
 *
 * $Id$
 */
package arquitectura.validation;

import arquitectura.CapaAccesoDatos;
import arquitectura.CapaLogicaNegocio;
import arquitectura.CapaPersistencia;
import arquitectura.CapaPresentacion;
import arquitectura.CapaServicio;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link arquitectura.RootSistema}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootSistemaValidator {
	boolean validate();

	boolean validatePresentaciones(EList<CapaPresentacion> value);
	boolean validateCapaLogicaNegocio(CapaLogicaNegocio value);
	boolean validateCapaServicio(CapaServicio value);
	boolean validateCapaAccesoDatos(CapaAccesoDatos value);
	boolean validateCapaPersistencia(CapaPersistencia value);
}
