/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EstilosUiModule extends org.xtext.ui.AbstractEstilosUiModule {
	public EstilosUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
