/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.CatalogoGrammarAccess;

public class CatalogoParser extends AbstractContentAssistParser {
	
	@Inject
	private CatalogoGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalCatalogoParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalCatalogoParser result = new org.xtext.ui.contentassist.antlr.internal.InternalCatalogoParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getRootSistemaAccess().getGroup(), "rule__RootSistema__Group__0");
					put(grammarAccess.getEmpresaAccess().getGroup(), "rule__Empresa__Group__0");
					put(grammarAccess.getEmpresaAccess().getGroup_2(), "rule__Empresa__Group_2__0");
					put(grammarAccess.getEmpresaAccess().getGroup_3(), "rule__Empresa__Group_3__0");
					put(grammarAccess.getEmpresaAccess().getGroup_4(), "rule__Empresa__Group_4__0");
					put(grammarAccess.getEmpresaAccess().getGroup_5(), "rule__Empresa__Group_5__0");
					put(grammarAccess.getEmpresaAccess().getGroup_6(), "rule__Empresa__Group_6__0");
					put(grammarAccess.getEmpresaAccess().getGroup_7(), "rule__Empresa__Group_7__0");
					put(grammarAccess.getCatalogoAccess().getGroup(), "rule__Catalogo__Group__0");
					put(grammarAccess.getCatalogoAccess().getGroup_2(), "rule__Catalogo__Group_2__0");
					put(grammarAccess.getCatalogoAccess().getGroup_3(), "rule__Catalogo__Group_3__0");
					put(grammarAccess.getCatalogoAccess().getGroup_7(), "rule__Catalogo__Group_7__0");
					put(grammarAccess.getELongAccess().getGroup(), "rule__ELong__Group__0");
					put(grammarAccess.getCategoriaAccess().getGroup(), "rule__Categoria__Group__0");
					put(grammarAccess.getCategoriaAccess().getGroup_2(), "rule__Categoria__Group_2__0");
					put(grammarAccess.getCategoriaAccess().getGroup_3(), "rule__Categoria__Group_3__0");
					put(grammarAccess.getCategoriaAccess().getGroup_7(), "rule__Categoria__Group_7__0");
					put(grammarAccess.getProductoAccess().getGroup(), "rule__Producto__Group__0");
					put(grammarAccess.getProductoAccess().getGroup_2(), "rule__Producto__Group_2__0");
					put(grammarAccess.getProductoAccess().getGroup_3(), "rule__Producto__Group_3__0");
					put(grammarAccess.getProductoAccess().getGroup_7(), "rule__Producto__Group_7__0");
					put(grammarAccess.getAtributoAccess().getGroup(), "rule__Atributo__Group__0");
					put(grammarAccess.getAtributoAccess().getGroup_3(), "rule__Atributo__Group_3__0");
					put(grammarAccess.getAtributoAccess().getGroup_4(), "rule__Atributo__Group_4__0");
					put(grammarAccess.getAtributoAccess().getGroup_5(), "rule__Atributo__Group_5__0");
					put(grammarAccess.getAtributoAccess().getGroup_6(), "rule__Atributo__Group_6__0");
					put(grammarAccess.getRootSistemaAccess().getEmpresaAssignment_3(), "rule__RootSistema__EmpresaAssignment_3");
					put(grammarAccess.getEmpresaAccess().getNombreAssignment_2_1(), "rule__Empresa__NombreAssignment_2_1");
					put(grammarAccess.getEmpresaAccess().getDireccionAssignment_3_1(), "rule__Empresa__DireccionAssignment_3_1");
					put(grammarAccess.getEmpresaAccess().getEmailAssignment_4_1(), "rule__Empresa__EmailAssignment_4_1");
					put(grammarAccess.getEmpresaAccess().getTelefonoAssignment_5_1(), "rule__Empresa__TelefonoAssignment_5_1");
					put(grammarAccess.getEmpresaAccess().getDescripcionAssignment_6_1(), "rule__Empresa__DescripcionAssignment_6_1");
					put(grammarAccess.getEmpresaAccess().getUrlImagenAssignment_7_1(), "rule__Empresa__UrlImagenAssignment_7_1");
					put(grammarAccess.getEmpresaAccess().getCatalogoAssignment_9(), "rule__Empresa__CatalogoAssignment_9");
					put(grammarAccess.getCatalogoAccess().getIdCatalogoAssignment_2_1(), "rule__Catalogo__IdCatalogoAssignment_2_1");
					put(grammarAccess.getCatalogoAccess().getNombreAssignment_3_1(), "rule__Catalogo__NombreAssignment_3_1");
					put(grammarAccess.getCatalogoAccess().getCategoriasAssignment_6(), "rule__Catalogo__CategoriasAssignment_6");
					put(grammarAccess.getCatalogoAccess().getCategoriasAssignment_7_1(), "rule__Catalogo__CategoriasAssignment_7_1");
					put(grammarAccess.getCategoriaAccess().getIdCategoriaAssignment_2_1(), "rule__Categoria__IdCategoriaAssignment_2_1");
					put(grammarAccess.getCategoriaAccess().getNombreAssignment_3_1(), "rule__Categoria__NombreAssignment_3_1");
					put(grammarAccess.getCategoriaAccess().getProductosAssignment_6(), "rule__Categoria__ProductosAssignment_6");
					put(grammarAccess.getCategoriaAccess().getProductosAssignment_7_1(), "rule__Categoria__ProductosAssignment_7_1");
					put(grammarAccess.getProductoAccess().getIdProductoAssignment_2_1(), "rule__Producto__IdProductoAssignment_2_1");
					put(grammarAccess.getProductoAccess().getNombreAssignment_3_1(), "rule__Producto__NombreAssignment_3_1");
					put(grammarAccess.getProductoAccess().getAtributosAssignment_6(), "rule__Producto__AtributosAssignment_6");
					put(grammarAccess.getProductoAccess().getAtributosAssignment_7_1(), "rule__Producto__AtributosAssignment_7_1");
					put(grammarAccess.getAtributoAccess().getIdAtributoAssignment_3_1(), "rule__Atributo__IdAtributoAssignment_3_1");
					put(grammarAccess.getAtributoAccess().getNombreAtributoAssignment_4_1(), "rule__Atributo__NombreAtributoAssignment_4_1");
					put(grammarAccess.getAtributoAccess().getValorAtributoAssignment_5_1(), "rule__Atributo__ValorAtributoAssignment_5_1");
					put(grammarAccess.getAtributoAccess().getTipoDatoAssignment_6_1(), "rule__Atributo__TipoDatoAssignment_6_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalCatalogoParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalCatalogoParser) parser;
			typedParser.entryRuleRootSistema();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public CatalogoGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CatalogoGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
