/**
 *
 * $Id$
 */
package estilos.validation;

import estilos.TamanoLetra;

/**
 * A sample validator interface for {@link estilos.Letra}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LetraValidator {
	boolean validate();

	boolean validateColorLetra(String value);
	boolean validateFuente(String value);
	boolean validateTamano(TamanoLetra value);
}
