/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist

import org.xtext.ui.contentassist.AbstractCatalogoProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class CatalogoProposalProvider extends AbstractCatalogoProposalProvider {
}
