/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist

import org.xtext.ui.contentassist.AbstractEstilosProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EstilosProposalProvider extends AbstractEstilosProposalProvider {
}
